image: python:3.9

stages:
  - publish
  - release

variables:
  POETRY_VERSION: 1.5.1

publish:
  stage: publish
  before_script:
    - curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3 -
    - export PATH="/root/.local/bin:$PATH"
    - poetry install
    - poetry source add --priority=supplemental gitlab https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi
    - poetry config repositories.gitlab https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi
    - poetry config http-basic.gitlab gitlab-ci-token $CI_JOB_TOKEN

  script:
    - poetry version $CI_COMMIT_TAG
    - poetry publish --build --repository gitlab
  only:
    - tags
  except:
    - branches

create_release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: publish
  script:
    - echo "Create Release $tag"
  release:
    name: "Release $CI_COMMIT_TAG"
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG"
