image: python:3.9

stages:
  - build

variables:
  POETRY_VERSION: 1.5.1

before_script:
  - curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3 -
  - export PATH="/root/.local/bin:$PATH"
  - poetry install
  - poetry source add --priority=supplemental gitlab https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi
  - poetry config repositories.gitlab https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/pypi
  - poetry config http-basic.gitlab gitlab-ci-token $CI_JOB_TOKEN

build:
  stage: build
  script:
    - poetry publish --build --repository gitlab
  artifacts:
    paths:
      - dist/*.whl
