image: python:3.9

stages:
  - build

variables:
  POETRY_VERSION: 1.5.1

before_script:
  - curl -sSL https://install.python-poetry.org | POETRY_VERSION=$POETRY_VERSION python3 -
  - export PATH="/root/.local/bin:$PATH"
  - poetry install

build:
  stage: build
  script:
    - poetry build
  artifacts:
    paths:
      - dist/*.whl
