from enum import Enum


class TranscoderUsagesElasticSchemaTranscoderType(str, Enum):
    AMAZON_REKOGNITION_IMAGE = "AMAZON_REKOGNITION_IMAGE"
    AMAZON_REKOGNITION_VIDEO = "AMAZON_REKOGNITION_VIDEO"
    AMAZON_TRANSCRIBE = "AMAZON_TRANSCRIBE"
    COLLECTION_KEYFRAMES = "COLLECTION_KEYFRAMES"
    ELEMENTAL_MEDIACONVERT = "ELEMENTAL_MEDIACONVERT"
    ELEMENTAL_SERVER = "ELEMENTAL_SERVER"
    ENCODING_COM = "ENCODING_COM"
    FACE_RECOGNITION = "FACE_RECOGNITION"
    FFMPEG = "FFMPEG"
    FFMPEG_FIRST_FRAME = "FFMPEG_FIRST_FRAME"
    FLICS = "FLICS"
    GCVI_TRANSCRIPTION = "GCVI_TRANSCRIPTION"
    GOOGLE_VIDEO_INTELLIGENCE = "GOOGLE_VIDEO_INTELLIGENCE"
    GOOGLE_VISION = "GOOGLE_VISION"
    ICONIK_EDGE_TRANSCODER = "ICONIK_EDGE_TRANSCODER"
    IMAGEMAGICK = "IMAGEMAGICK"
    LIBREOFFICE = "LIBREOFFICE"
    MEDIAINFO = "MEDIAINFO"
    NONE = "NONE"
    OPEN_GRAPH = "OPEN_GRAPH"
    REV_AI_TRANSCRIPTION = "REV_AI_TRANSCRIPTION"
    SUBTITLES = "SUBTITLES"
    TELESTREAM_CLOUD = "TELESTREAM_CLOUD"
    VANTAGE = "VANTAGE"
    WILDMOKA = "WILDMOKA"
    ZENCODER = "ZENCODER"

    def __str__(self) -> str:
        return str(self.value)
