from enum import Enum


class TranscoderUsagesElasticSchemaOperationType(str, Enum):
    ANALYZE = "ANALYZE"
    CONFORM = "CONFORM"
    EXTRACT_AUDIO = "EXTRACT_AUDIO"
    EXTRACT_IMAGE = "EXTRACT_IMAGE"
    FACE_RECOGNITION_IMAGE = "FACE_RECOGNITION_IMAGE"
    FACE_RECOGNITION_VIDEO = "FACE_RECOGNITION_VIDEO"
    MEDIAINFO = "MEDIAINFO"
    TRANSCODE = "TRANSCODE"
    TRANSCODE_AUDIO = "TRANSCODE_AUDIO"
    TRANSCODE_IMAGE = "TRANSCODE_IMAGE"
    TRANSCODE_KEYFRAMES = "TRANSCODE_KEYFRAMES"
    TRANSCODE_VIDEO = "TRANSCODE_VIDEO"
    TRANSCRIBE = "TRANSCRIBE"
    TRANSCRIBE_HUMAN = "TRANSCRIBE_HUMAN"

    def __str__(self) -> str:
        return str(self.value)
