from enum import Enum


class AssetHistorySchemaOperationType(str, Enum):
    ADD_FORMAT = "ADD_FORMAT"
    ANALYZE = "ANALYZE"
    APPROVE = "APPROVE"
    ARCHIVE = "ARCHIVE"
    CUSTOM = "CUSTOM"
    DELETE = "DELETE"
    DELETE_FILE = "DELETE_FILE"
    DELETE_FILESET = "DELETE_FILESET"
    DELETE_FORMAT = "DELETE_FORMAT"
    DOWNLOAD = "DOWNLOAD"
    EXPORT = "EXPORT"
    FACE_RECOGNITION = "FACE_RECOGNITION"
    METADATA = "METADATA"
    MODIFY_FILESET = "MODIFY_FILESET"
    REJECT = "REJECT"
    RESTORE = "RESTORE"
    RESTORE_ARCHIVE = "RESTORE_ARCHIVE"
    RESTORE_FILESET = "RESTORE_FILESET"
    RESTORE_FORMAT = "RESTORE_FORMAT"
    RESTORE_FROM_GLACIER = "RESTORE_FROM_GLACIER"
    TRANSCODE = "TRANSCODE"
    TRANSCRIPTION = "TRANSCRIPTION"
    TRANSFER = "TRANSFER"
    UNLINK_SUBCLIP = "UNLINK_SUBCLIP"
    VERSION_CREATE = "VERSION_CREATE"
    VERSION_DELETE = "VERSION_DELETE"
    VERSION_PROMOTE = "VERSION_PROMOTE"
    VERSION_UPDATE = "VERSION_UPDATE"

    def __str__(self) -> str:
        return str(self.value)
