from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.file_create_schema_status import FileCreateSchemaStatus
from ..models.file_create_schema_template_engine import FileCreateSchemaTemplateEngine
from ..models.file_create_schema_type import FileCreateSchemaType
from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.file_create_schema_upload_credentials_type_0 import (
        FileCreateSchemaUploadCredentialsType0,
    )


T = TypeVar("T", bound="FileCreateSchema")


@_attrs_define
class FileCreateSchema:
    """
    Attributes:
        directory_path (str):
        original_name (str):
        type_ (FileCreateSchemaType):
        asset_id (None | Unset | UUID):
        checksum (None | str | Unset):
        content_type (None | str | Unset):
        date_created (datetime.datetime | None | Unset):
        date_modified (datetime.datetime | None | Unset):
        file_date_created (datetime.datetime | None | Unset):
        file_date_modified (datetime.datetime | None | Unset):
        file_set_id (None | Unset | UUID):
        format_id (None | Unset | UUID):
        id (None | Unset | UUID):
        multipart_upload_url (None | str | Unset):
        name (None | str | Unset): If not specified, name will be autogenerated based on `id` and `original_name`
        parent_id (None | Unset | UUID):
        size (int | None | Unset):
        status (FileCreateSchemaStatus | None | Unset):
        storage_id (None | Unset | UUID):
        storage_method (None | str | Unset):
        template (None | str | Unset):
        template_engine (FileCreateSchemaTemplateEngine | None | Unset):
        upload_credentials (FileCreateSchemaUploadCredentialsType0 | None | Unset):
        upload_filename (None | str | Unset):
        upload_method (None | str | Unset):
        upload_url (None | str | Unset):
        user_id (None | Unset | UUID):
        version_id (None | Unset | UUID):
    """

    directory_path: str
    original_name: str
    type_: FileCreateSchemaType
    asset_id: None | Unset | UUID = UNSET
    checksum: None | str | Unset = UNSET
    content_type: None | str | Unset = UNSET
    date_created: datetime.datetime | None | Unset = UNSET
    date_modified: datetime.datetime | None | Unset = UNSET
    file_date_created: datetime.datetime | None | Unset = UNSET
    file_date_modified: datetime.datetime | None | Unset = UNSET
    file_set_id: None | Unset | UUID = UNSET
    format_id: None | Unset | UUID = UNSET
    id: None | Unset | UUID = UNSET
    multipart_upload_url: None | str | Unset = UNSET
    name: None | str | Unset = UNSET
    parent_id: None | Unset | UUID = UNSET
    size: int | None | Unset = UNSET
    status: FileCreateSchemaStatus | None | Unset = UNSET
    storage_id: None | Unset | UUID = UNSET
    storage_method: None | str | Unset = UNSET
    template: None | str | Unset = UNSET
    template_engine: FileCreateSchemaTemplateEngine | None | Unset = UNSET
    upload_credentials: FileCreateSchemaUploadCredentialsType0 | None | Unset = UNSET
    upload_filename: None | str | Unset = UNSET
    upload_method: None | str | Unset = UNSET
    upload_url: None | str | Unset = UNSET
    user_id: None | Unset | UUID = UNSET
    version_id: None | Unset | UUID = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        from ..models.file_create_schema_upload_credentials_type_0 import (
            FileCreateSchemaUploadCredentialsType0,
        )

        directory_path = self.directory_path

        original_name = self.original_name

        type_ = self.type_.value

        asset_id: None | str | Unset
        if isinstance(self.asset_id, Unset):
            asset_id = UNSET
        elif isinstance(self.asset_id, UUID):
            asset_id = str(self.asset_id)
        else:
            asset_id = self.asset_id

        checksum: None | str | Unset
        if isinstance(self.checksum, Unset):
            checksum = UNSET
        else:
            checksum = self.checksum

        content_type: None | str | Unset
        if isinstance(self.content_type, Unset):
            content_type = UNSET
        else:
            content_type = self.content_type

        date_created: None | str | Unset
        if isinstance(self.date_created, Unset):
            date_created = UNSET
        elif isinstance(self.date_created, datetime.datetime):
            date_created = self.date_created.isoformat()
        else:
            date_created = self.date_created

        date_modified: None | str | Unset
        if isinstance(self.date_modified, Unset):
            date_modified = UNSET
        elif isinstance(self.date_modified, datetime.datetime):
            date_modified = self.date_modified.isoformat()
        else:
            date_modified = self.date_modified

        file_date_created: None | str | Unset
        if isinstance(self.file_date_created, Unset):
            file_date_created = UNSET
        elif isinstance(self.file_date_created, datetime.datetime):
            file_date_created = self.file_date_created.isoformat()
        else:
            file_date_created = self.file_date_created

        file_date_modified: None | str | Unset
        if isinstance(self.file_date_modified, Unset):
            file_date_modified = UNSET
        elif isinstance(self.file_date_modified, datetime.datetime):
            file_date_modified = self.file_date_modified.isoformat()
        else:
            file_date_modified = self.file_date_modified

        file_set_id: None | str | Unset
        if isinstance(self.file_set_id, Unset):
            file_set_id = UNSET
        elif isinstance(self.file_set_id, UUID):
            file_set_id = str(self.file_set_id)
        else:
            file_set_id = self.file_set_id

        format_id: None | str | Unset
        if isinstance(self.format_id, Unset):
            format_id = UNSET
        elif isinstance(self.format_id, UUID):
            format_id = str(self.format_id)
        else:
            format_id = self.format_id

        id: None | str | Unset
        if isinstance(self.id, Unset):
            id = UNSET
        elif isinstance(self.id, UUID):
            id = str(self.id)
        else:
            id = self.id

        multipart_upload_url: None | str | Unset
        if isinstance(self.multipart_upload_url, Unset):
            multipart_upload_url = UNSET
        else:
            multipart_upload_url = self.multipart_upload_url

        name: None | str | Unset
        if isinstance(self.name, Unset):
            name = UNSET
        else:
            name = self.name

        parent_id: None | str | Unset
        if isinstance(self.parent_id, Unset):
            parent_id = UNSET
        elif isinstance(self.parent_id, UUID):
            parent_id = str(self.parent_id)
        else:
            parent_id = self.parent_id

        size: int | None | Unset
        if isinstance(self.size, Unset):
            size = UNSET
        else:
            size = self.size

        status: None | str | Unset
        if isinstance(self.status, Unset):
            status = UNSET
        elif isinstance(self.status, FileCreateSchemaStatus):
            status = self.status.value
        else:
            status = self.status

        storage_id: None | str | Unset
        if isinstance(self.storage_id, Unset):
            storage_id = UNSET
        elif isinstance(self.storage_id, UUID):
            storage_id = str(self.storage_id)
        else:
            storage_id = self.storage_id

        storage_method: None | str | Unset
        if isinstance(self.storage_method, Unset):
            storage_method = UNSET
        else:
            storage_method = self.storage_method

        template: None | str | Unset
        if isinstance(self.template, Unset):
            template = UNSET
        else:
            template = self.template

        template_engine: None | str | Unset
        if isinstance(self.template_engine, Unset):
            template_engine = UNSET
        elif isinstance(self.template_engine, FileCreateSchemaTemplateEngine):
            template_engine = self.template_engine.value
        else:
            template_engine = self.template_engine

        upload_credentials: dict[str, Any] | None | Unset
        if isinstance(self.upload_credentials, Unset):
            upload_credentials = UNSET
        elif isinstance(
            self.upload_credentials, FileCreateSchemaUploadCredentialsType0
        ):
            upload_credentials = self.upload_credentials.to_dict()
        else:
            upload_credentials = self.upload_credentials

        upload_filename: None | str | Unset
        if isinstance(self.upload_filename, Unset):
            upload_filename = UNSET
        else:
            upload_filename = self.upload_filename

        upload_method: None | str | Unset
        if isinstance(self.upload_method, Unset):
            upload_method = UNSET
        else:
            upload_method = self.upload_method

        upload_url: None | str | Unset
        if isinstance(self.upload_url, Unset):
            upload_url = UNSET
        else:
            upload_url = self.upload_url

        user_id: None | str | Unset
        if isinstance(self.user_id, Unset):
            user_id = UNSET
        elif isinstance(self.user_id, UUID):
            user_id = str(self.user_id)
        else:
            user_id = self.user_id

        version_id: None | str | Unset
        if isinstance(self.version_id, Unset):
            version_id = UNSET
        elif isinstance(self.version_id, UUID):
            version_id = str(self.version_id)
        else:
            version_id = self.version_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "directory_path": directory_path,
                "original_name": original_name,
                "type": type_,
            }
        )
        if asset_id is not UNSET:
            field_dict["asset_id"] = asset_id
        if checksum is not UNSET:
            field_dict["checksum"] = checksum
        if content_type is not UNSET:
            field_dict["content_type"] = content_type
        if date_created is not UNSET:
            field_dict["date_created"] = date_created
        if date_modified is not UNSET:
            field_dict["date_modified"] = date_modified
        if file_date_created is not UNSET:
            field_dict["file_date_created"] = file_date_created
        if file_date_modified is not UNSET:
            field_dict["file_date_modified"] = file_date_modified
        if file_set_id is not UNSET:
            field_dict["file_set_id"] = file_set_id
        if format_id is not UNSET:
            field_dict["format_id"] = format_id
        if id is not UNSET:
            field_dict["id"] = id
        if multipart_upload_url is not UNSET:
            field_dict["multipart_upload_url"] = multipart_upload_url
        if name is not UNSET:
            field_dict["name"] = name
        if parent_id is not UNSET:
            field_dict["parent_id"] = parent_id
        if size is not UNSET:
            field_dict["size"] = size
        if status is not UNSET:
            field_dict["status"] = status
        if storage_id is not UNSET:
            field_dict["storage_id"] = storage_id
        if storage_method is not UNSET:
            field_dict["storage_method"] = storage_method
        if template is not UNSET:
            field_dict["template"] = template
        if template_engine is not UNSET:
            field_dict["template_engine"] = template_engine
        if upload_credentials is not UNSET:
            field_dict["upload_credentials"] = upload_credentials
        if upload_filename is not UNSET:
            field_dict["upload_filename"] = upload_filename
        if upload_method is not UNSET:
            field_dict["upload_method"] = upload_method
        if upload_url is not UNSET:
            field_dict["upload_url"] = upload_url
        if user_id is not UNSET:
            field_dict["user_id"] = user_id
        if version_id is not UNSET:
            field_dict["version_id"] = version_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.file_create_schema_upload_credentials_type_0 import (
            FileCreateSchemaUploadCredentialsType0,
        )

        d = dict(src_dict)
        directory_path = d.pop("directory_path")

        original_name = d.pop("original_name")

        type_ = FileCreateSchemaType(d.pop("type"))

        def _parse_asset_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                asset_id_type_0 = UUID(data)

                return asset_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        asset_id = _parse_asset_id(d.pop("asset_id", UNSET))

        def _parse_checksum(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        checksum = _parse_checksum(d.pop("checksum", UNSET))

        def _parse_content_type(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        content_type = _parse_content_type(d.pop("content_type", UNSET))

        def _parse_date_created(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                date_created_type_0 = datetime.datetime.fromisoformat(data)

                return date_created_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        date_created = _parse_date_created(d.pop("date_created", UNSET))

        def _parse_date_modified(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                date_modified_type_0 = datetime.datetime.fromisoformat(data)

                return date_modified_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        date_modified = _parse_date_modified(d.pop("date_modified", UNSET))

        def _parse_file_date_created(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                file_date_created_type_0 = datetime.datetime.fromisoformat(data)

                return file_date_created_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        file_date_created = _parse_file_date_created(d.pop("file_date_created", UNSET))

        def _parse_file_date_modified(data: object) -> datetime.datetime | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                file_date_modified_type_0 = datetime.datetime.fromisoformat(data)

                return file_date_modified_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(datetime.datetime | None | Unset, data)

        file_date_modified = _parse_file_date_modified(
            d.pop("file_date_modified", UNSET)
        )

        def _parse_file_set_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                file_set_id_type_0 = UUID(data)

                return file_set_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        file_set_id = _parse_file_set_id(d.pop("file_set_id", UNSET))

        def _parse_format_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                format_id_type_0 = UUID(data)

                return format_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        format_id = _parse_format_id(d.pop("format_id", UNSET))

        def _parse_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                id_type_0 = UUID(data)

                return id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        id = _parse_id(d.pop("id", UNSET))

        def _parse_multipart_upload_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        multipart_upload_url = _parse_multipart_upload_url(
            d.pop("multipart_upload_url", UNSET)
        )

        def _parse_name(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        name = _parse_name(d.pop("name", UNSET))

        def _parse_parent_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                parent_id_type_0 = UUID(data)

                return parent_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        parent_id = _parse_parent_id(d.pop("parent_id", UNSET))

        def _parse_size(data: object) -> int | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(int | None | Unset, data)

        size = _parse_size(d.pop("size", UNSET))

        def _parse_status(data: object) -> FileCreateSchemaStatus | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                status_type_1 = FileCreateSchemaStatus(data)

                return status_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(FileCreateSchemaStatus | None | Unset, data)

        status = _parse_status(d.pop("status", UNSET))

        def _parse_storage_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                storage_id_type_0 = UUID(data)

                return storage_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        storage_id = _parse_storage_id(d.pop("storage_id", UNSET))

        def _parse_storage_method(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        storage_method = _parse_storage_method(d.pop("storage_method", UNSET))

        def _parse_template(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        template = _parse_template(d.pop("template", UNSET))

        def _parse_template_engine(
            data: object,
        ) -> FileCreateSchemaTemplateEngine | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                template_engine_type_1 = FileCreateSchemaTemplateEngine(data)

                return template_engine_type_1
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(FileCreateSchemaTemplateEngine | None | Unset, data)

        template_engine = _parse_template_engine(d.pop("template_engine", UNSET))

        def _parse_upload_credentials(
            data: object,
        ) -> FileCreateSchemaUploadCredentialsType0 | None | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, dict):
                    raise TypeError()
                upload_credentials_type_0 = (
                    FileCreateSchemaUploadCredentialsType0.from_dict(data)
                )

                return upload_credentials_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(FileCreateSchemaUploadCredentialsType0 | None | Unset, data)

        upload_credentials = _parse_upload_credentials(
            d.pop("upload_credentials", UNSET)
        )

        def _parse_upload_filename(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        upload_filename = _parse_upload_filename(d.pop("upload_filename", UNSET))

        def _parse_upload_method(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        upload_method = _parse_upload_method(d.pop("upload_method", UNSET))

        def _parse_upload_url(data: object) -> None | str | Unset:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            return cast(None | str | Unset, data)

        upload_url = _parse_upload_url(d.pop("upload_url", UNSET))

        def _parse_user_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                user_id_type_0 = UUID(data)

                return user_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        user_id = _parse_user_id(d.pop("user_id", UNSET))

        def _parse_version_id(data: object) -> None | Unset | UUID:
            if data is None:
                return data
            if isinstance(data, Unset):
                return data
            try:
                if not isinstance(data, str):
                    raise TypeError()
                version_id_type_0 = UUID(data)

                return version_id_type_0
            except (TypeError, ValueError, AttributeError, KeyError):
                pass
            return cast(None | Unset | UUID, data)

        version_id = _parse_version_id(d.pop("version_id", UNSET))

        file_create_schema = cls(
            directory_path=directory_path,
            original_name=original_name,
            type_=type_,
            asset_id=asset_id,
            checksum=checksum,
            content_type=content_type,
            date_created=date_created,
            date_modified=date_modified,
            file_date_created=file_date_created,
            file_date_modified=file_date_modified,
            file_set_id=file_set_id,
            format_id=format_id,
            id=id,
            multipart_upload_url=multipart_upload_url,
            name=name,
            parent_id=parent_id,
            size=size,
            status=status,
            storage_id=storage_id,
            storage_method=storage_method,
            template=template,
            template_engine=template_engine,
            upload_credentials=upload_credentials,
            upload_filename=upload_filename,
            upload_method=upload_method,
            upload_url=upload_url,
            user_id=user_id,
            version_id=version_id,
        )

        file_create_schema.additional_properties = d
        return file_create_schema

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
