from enum import Enum


class IconikStorageGatewayEventSchemaType(str, Enum):
    ABORT_COLLECTION_MAP = "ABORT_COLLECTION_MAP"
    ABORT_JOBS_BULK = "ABORT_JOBS_BULK"
    ASSET_MERGED = "ASSET_MERGED"
    COLLECTION_DELETED = "COLLECTION_DELETED"
    DELETE = "DELETE"
    DOWNLOAD = "DOWNLOAD"
    DOWNLOAD_ABORT = "DOWNLOAD_ABORT"
    DOWNLOAD_CHANGE_PRIORITY = "DOWNLOAD_CHANGE_PRIORITY"
    INGEST_UPLOAD = "INGEST_UPLOAD"
    MARK_MISSING_OUTSIDE_SCAN_DIRS = "MARK_MISSING_OUTSIDE_SCAN_DIRS"
    REQUEST_COLLECTION_MAP = "REQUEST_COLLECTION_MAP"
    RESET_INGEST_VALIDATION = "RESET_INGEST_VALIDATION"
    RESTART = "RESTART"
    SCHEDULE_CHECKSUM_CALCULATION = "SCHEDULE_CHECKSUM_CALCULATION"
    TRANSCODE = "TRANSCODE"
    TRANSCODE_ABORT = "TRANSCODE_ABORT"
    TRANSCODE_CHANGE_PRIORITY = "TRANSCODE_CHANGE_PRIORITY"
    UPLOAD = "UPLOAD"
    UPLOAD_ABORT = "UPLOAD_ABORT"
    UPLOAD_CHANGE_PRIORITY = "UPLOAD_CHANGE_PRIORITY"

    def __str__(self) -> str:
        return str(self.value)
