from enum import Enum


class TranscoderReadSchemaType(str, Enum):
    EDITREADY = "EDITREADY"
    EDIT_PROXY = "EDIT_PROXY"
    ELEMENTAL_MEDIACONVERT = "ELEMENTAL_MEDIACONVERT"
    ELEMENTAL_SERVER = "ELEMENTAL_SERVER"
    ENCODING_COM = "ENCODING_COM"
    FFMPEG = "FFMPEG"
    FLICS = "FLICS"
    ICONIK_EDGE_TRANSCODER = "ICONIK_EDGE_TRANSCODER"
    IMAGEMAGICK = "IMAGEMAGICK"
    LIBREOFFICE = "LIBREOFFICE"
    REDLINE = "REDLINE"
    TELESTREAM_CLOUD = "TELESTREAM_CLOUD"
    VANTAGE = "VANTAGE"
    WATCH_FOLDER_VIDEO = "WATCH_FOLDER_VIDEO"
    WILDMOKA = "WILDMOKA"
    ZENCODER = "ZENCODER"

    def __str__(self) -> str:
        return str(self.value)
