from enum import Enum


class SystemDomainSuperAdminSchemaIndustry(str, Enum):
    ADVERTISING_MARKETING_CREATIVE = "ADVERTISING_MARKETING_CREATIVE"
    AUTOMOTIVE = "AUTOMOTIVE"
    BROADCASTER_NETWORKS = "BROADCASTER_NETWORKS"
    CONSTRUCTION_MANUFACTURING = "CONSTRUCTION_MANUFACTURING"
    EDUCATION = "EDUCATION"
    ENERGY_UTILITIES = "ENERGY_UTILITIES"
    FAITH_RELIGIOUS_ORGS = "FAITH_RELIGIOUS_ORGS"
    FINANCE = "FINANCE"
    GAME_STUDIOS_PUBLISHERS = "GAME_STUDIOS_PUBLISHERS"
    GOVERNMENT_PUBLIC_SECTOR = "GOVERNMENT_PUBLIC_SECTOR"
    HEALTHCARE = "HEALTHCARE"
    HOSPITALITY_FITNESS_WELLNESS = "HOSPITALITY_FITNESS_WELLNESS"
    LIVE_PRODUCTION_EVENTS = "LIVE_PRODUCTION_EVENTS"
    MEDIA_CONGLOMERATES = "MEDIA_CONGLOMERATES"
    NONPROFITS_NON_RELIGIOUS = "NONPROFITS_NON_RELIGIOUS"
    ONLINE_MEDIA = "ONLINE_MEDIA"
    OTHER = "OTHER"
    PUBLISHERS_NEWSPAPERS = "PUBLISHERS_NEWSPAPERS"
    RETAIL_CONSUMER_GOODS = "RETAIL_CONSUMER_GOODS"
    SOFTWARE_TECHNOLOGY = "SOFTWARE_TECHNOLOGY"
    SPORTS_RIGHTS_LEAGUES = "SPORTS_RIGHTS_LEAGUES"
    STUDIOS_CONTENT_PRODUCERS = "STUDIOS_CONTENT_PRODUCERS"
    TELECOMMUNICATIONS = "TELECOMMUNICATIONS"

    def __str__(self) -> str:
        return str(self.value)
